### ISSUE TITLE
Agility Skill Script Process

### ISSUE THREAD

**Issue by Indestructoyed** [BehrRiley/Gielinor#2]

**Comment by BehrRiley** [comment]
A few notes I forgot to throw into that file;
The scripts process is rolling based on the Agility level of the player, which is going to use the tag `<player.flag[AgilityLevel]>`.
You already added the cause type we'll need being `FALL` damage enum that I forgot to include also, so thanks.

**Comment by BehrRiley** [comment]
Skills added, closed
